apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: mediawiki-persistent-storage
          mountPath: /var/www/mediawiki
      volumes:
      - name: mediawiki-persistent-storage
        persistentVolumeClaim:
          claimName: mediawiki-pvc
